### ISSUE TITLE
ughhhh

### ISSUE THREAD

**Issue by the1mills** [shoebappa/vagrant-meteor-windows#32]
this tutorial does not do a good enough job of saying where we install things on the native machine and where we install things on the virtual machine.

For example, we clearly install Git, VirtualBox and Vagrant on the native machine,

but after that, it's not clear at which point we begin installing things on the VM.

Please make this demarcation much more clear.

**Comment by shoebappa** [comment]
The majority is installed on the host and it pretty clearly tells you how to vagrant ssh into the vm.  Feel free to submit a pull request with any edits that you think would make this more clear.
